import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./context/AuthContext";
import ToasterContext from "./context/ToasterContext";
import Link from "next/link";
import SignOut from "./components/SignOut";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ToasterContext />
          <div className="flex space-x-2">
            <Link href={"/"} className="text-2xl">
              Home
            </Link>
            <Link href={"/login"} className="text-2xl">
              Login
            </Link>
            <Link href={"/register"} className="text-2xl">
              Register
            </Link>
            <SignOut />
          </div>
          {children}
        </Provider>
      </body>
    </html>
  );
}
